apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
# spec for deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    #  pod config start
    metadata:
      labels:
        app: nginx
    # spec for a pod | blue print for a pod
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 8080
    # pod config end

