apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
    
spec:
  containers:
    - name: nginx-container
      image: nginx
# kubectl create -f sample-pod-definition.yaml --> this command will create a POD
