apiVersion: v1
kind: Secret
metadata:
    name: mongodb-secret
type: Opaque
data:
# base64 encoded value of root | echo -n "root" | base64 --> cm9vdA==
    mongo-root-username: cm9vdA==
    mongo-root-password: cm9vdA==
